version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
universal_ores = true
easy_emerald = true
farmersdelight = true
supplementaries = true
friendsandfoes = true
oxidized = true
suppsquared = true
sawmill = true
createcasing = true
weeping_angels = true
create = true
piglinproliferation = true
enderitemod = true
easymagic = true
brewinandchewin = true
pointblank = true
sereneseasons = true
terrainslabs = true
gravestone = true
easyanvils = true
createoreexcavation = true
visualworkbench = true
minecraft = true
lootr = true
gigeresque = true
ends_delight = true
extradelight = true
expandedstorage = true
ore_creeper = true
trading_floor = true
travelersbackpack = true
create_things_and_misc = true
fastpaintings = true
bellsandwhistles = true
createframed = true
amendments = true
mynethersdelight = true
create_d2d = true
ditr = true
snowrealmagic = true
enchantinginfuser = true
morevillagers = true
illagerinvasion = true
gardens_of_the_dead = true
azurelib = true
disenchanting_table = true
