[General]
	# Default: 4.0
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.0

["Coal Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 3.0
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 320

["Copper Creeper"]
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 112
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.0

["Diamond Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 1.0
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 16

["Emerald Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.5
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 320

["Gold Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 1.75
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 32

["Iron Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.0
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 320

["Lapis Lazuli Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.5
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 64

["Nether Gold Creeper"]
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 240
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.25

["Nether Quartz Creeper"]
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 256
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.75

["Redstone Creeper"]
	# Default: 3.75
	# Range: 0.0 ~ 100.0
	"explosion radius" = 2.5
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 16

["Ancient Debris Creeper"]
	# Default: 320
	# Range: -64 ~ 320
	"max spawn Y level" = 256
	# Default: 1.0
	# Range: 0.0 ~ 100.0
	"explosion radius" = 1.0

#Configure Mob spawn weight & min/max group size. Set weight to 0 to disable.
["Coal Creeper - Fabric"]
	# Default: 30
	# Range: 0 ~ 500
	Weight = 30
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Copper Creeper - Fabric"]
	# Default: 30
	# Range: 0 ~ 500
	Weight = 30
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Diamond Creeper - Fabric"]
	# Default: 10
	# Range: 0 ~ 500
	Weight = 10
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Emerald Creeper - Fabric"]
	# Default: 10
	# Range: 0 ~ 500
	Weight = 10
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Gold Creeper - Fabric"]
	# Default: 30
	# Range: 0 ~ 500
	Weight = 30
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Iron Creeper - Fabric"]
	# Default: 40
	# Range: 0 ~ 500
	Weight = 40
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Lapis Lazuli Creeper - Fabric"]
	# Default: 25
	# Range: 0 ~ 500
	Weight = 25
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Redstone Creeper - Fabric"]
	# Default: 20
	# Range: 0 ~ 500
	Weight = 20
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Nether Gold Creeper - Fabric"]
	# Default: 10
	# Range: 0 ~ 500
	Weight = 10
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Nether Quartz Creeper - Fabric"]
	# Default: 10
	# Range: 0 ~ 500
	Weight = 10
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 2
	# Range: 0 ~ 100
	"Max Group Size" = 2

["Ancient Debris Creeper - Fabric"]
	# Default: 1
	# Range: 0 ~ 500
	Weight = 1
	# Default: 1
	# Range: 0 ~ 100
	"Min Group Size" = 1
	# Default: 1
	# Range: 0 ~ 100
	"Max Group Size" = 1
